app/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import index, signup, logout_view, todo, todos

urlpatterns = [
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('todo/', todos, name='todos'),
    path('todo/<int:todo_id>/', todo, name='todo')
]

urlpatterns += staticfiles_urlpatterns()

app_name = 'app'

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='auth'),
    path('', include('app.urls'), name='app'),
]

app/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Todo(models.Model):
    todo_text = models.CharField(max_length=300)
    is_done = models.BooleanField(default=False)
    todo_author = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.todo_text

    def as_dict(self):
        return {
            'todo_text': self.todo_text,
            'is_done': self.is_done,
            'pub_date': self.pub_date,
            'id': self.id
        }

app/views.py
import json

from django.contrib.auth.models import User
from django.core.serializers import serialize
from django.db import IntegrityError
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, authenticate, logout
from django.http import JsonResponse

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from app.models import Todo


def parse_body(body):
    return json.loads(body.decode('utf-8'))

def index(request):
    return render(request, 'registration/profile.html', {
        'title': 'Todo List App'
    })

def signup(request):
    message = ''
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
            if not username:
                message = 'Please provide a correct username'
            elif len(password) < 5:
                message = 'The password can\'t be less than 5 characters'
            else:
                user = User.objects.create_user(username, password=password)
                user.save()
                user = authenticate(username=username, password=password)
                login(request, user)
                return redirect(reverse('app:index'))

        except KeyError:
            message = 'Please fill in all the required fields'

        except IntegrityError:
            message = f'The username {request.POST["username"]} is already taken'

    return render(request, 'registration/signup.html', {
        'title': 'Sign up to our app', 'message': message
    })

def logout_view(request):
    logout(request)
    return render(request, 'registration/logout.html', {'title': 'Logged out successfully'})

@csrf_exempt
def todos(request):
    if not request.user.is_authenticated:
        return JsonResponse({'error': 'not authenticated'}, status=401)

    if request.method == 'POST':
        try:
            new_todo = parse_body(request.body)
            created_todo = request.user.todo_set.create(todo_text=new_todo['todo_text'])
            return JsonResponse(created_todo.as_dict(), status=201)
        except KeyError:
            return JsonResponse({'error': 'Please provide the todo'}, status=400)

    if request.method == 'GET':
        todos = [todo.as_dict() for todo in request.user.todo_set.order_by('-pub_date')]
        return JsonResponse(todos, safe=False)


@csrf_exempt
def todo(request, todo_id):
    if not request.user.is_authenticated:
        return JsonResponse({'error': 'not authenticated'}, status=401)

    if request.method == 'GET':
        try:
            todo = request.user.todo_set.get(id=todo_id)
            return JsonResponse(todo.as_dict())
        except Todo.DoesNotExist:
            return JsonResponse({'error': 'Todo not found'}, status=404)

    if request.method == 'PUT':
        try:
            todo = request.user.todo_set.get(id=todo_id)
            new_todo = parse_body(request.body)
            todo.is_done = new_todo.get('is_done') or todo.is_done
            todo.todo_text = new_todo.get('todo_text') or todo.todo_text

            todo.save()
            return JsonResponse(todo.as_dict())
        except Todo.DoesNotExist:
            return JsonResponse({'error': 'Todo not found'}, status=404)

    if request.method == 'DELETE':
        try:
            todo = request.user.todo_set.get(id=todo_id)
            todo.delete()
            return JsonResponse(todo.as_dict())
        except Todo.DoesNotExist:
            return JsonResponse({'error': 'Todo not found'}, status=404)

templates/components/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="teal">
        <div class="nav-wrapper container">
            <a href="/" class="brand-logo left">Todo list</a>
            <ul class="right" id="nav-mobile">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'app:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'app:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>